name: "CI Action"
description: "Composition of various CI steps used to ensure code is ready for merge."
runs:
  using: composite
  steps:
    - name: Check Formatting
      uses: ./.github/actions/format
    - name: Unit Tests
      uses: ./.github/actions/unit-tests
    - name: Integration Tests
      uses: ./.github/actions/integration-tests