name: On Pull Request

on:
  pull_request:
    # These can be configured to change when the CI job runs on pull request
    types: [opened, synchronize, reopened]
jobs:
  ci:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run CI
        uses: ./.github/actions/ci
