name: Test On Push

on:
  push:
    branches: [draft-ci-cd]
jobs:
  ci:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Formatting
        uses: ./.github/actions/format
      - name: Unit Tests
        uses: ./.github/actions/unit-tests
      - name: Integration Tests
        uses: ./.github/actions/integration-tests
