name: Test On Push

on:
  push:
    branches: [main]
jobs:
  ci:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run CI
        uses: ./.github/actions/ci
